import java.util.Scanner;
import java.util.Random;

public class NumberGame {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Random rn = new Random();
        int count = 5;
        System.out.println("Welcome In the Number Game!");
        System.out.println("Rules:");
        System.out.println("1.you have to enter a number. you will be given three rounds.");
        System.out.println("2.If the number generated by system matches your guess then you will be given 5 points.");
        System.out.println("3.if your guess is incorrect then you will be given zero. you have three good luck!");
        for (int i = 1; i <= 3; i++) {
            System.out.println("Round-" + i);
            for (int j = 1; j <= 3; j++) {

                System.out.print("Input the number: ");
                int guess_number = sc.nextInt();
                int random_number = rn.nextInt(100);
                System.out.println(random_number);
                if (guess_number == random_number) {
                    System.out.println("Correct Guess!wow your score is: " + count);
                } else if (guess_number != random_number) {
                    if (guess_number > random_number) {
                        System.out.println("oops!your guess is incorrect number is too low.");
                    } else {
                        System.out.println("oops!your guess is incorrect number is too low.");
                    }
                }
                if (j == 3) {
                    break;
                }
            }

        }
    }
}
